### ISSUE TITLE
does this still work ?

### ISSUE THREAD

**Issue by LazzaAU** [gmm96/Txt2SpeechBot#22]
Just checking if this still works or am i doing something wrong as i can't get it to do anything ?

If i type just @Txt2SpeechBot i still have the blue send arrow i click but nothing happens

If i type  @Txt2SpeechBot then some text like @Txt2SpeechBot hello the blue arrow disappears and i'm unable to send the message

cheers

**Comment by gabrieljaegerde** [comment]
Same thing. I just dropped the author a message on telegram. Let's see.

**Comment by gmm96** [comment]
Sorry, @Txt2SpeechBot is now offline. It will be available as soon as I have free time to reassemble the server.
Really sorry for the inconveniences.

**Comment by gmm96** [comment]
Hello buddies, bot @Txt2SpeechBot is online now in its newer version. You can check it on telegram.
