### ISSUE TITLE
Stop using and modifiying data structures from shared directly

### ISSUE THREAD

**Issue by alvarogzp** [gmm96/Txt2SpeechBot#3]
Instead, encapsulate them in classes to avoid having to deal with them in tts.py and saving them to persistent storage manually, etc.

**Comment by gmm96** [comment]
Thanks for the reminder. 
I think it will take very long, so I will probably start this enhancement on holidays.

**Comment by alvarogzp** [comment]
> Thanks for the reminder.
I think it will take very long, so I will probably start this enhancement on holidays.

time to do it :)

**Comment by gmm96** [comment]
> time to do it :)

I would like to start it right now, but I'm totally out of time.

**Comment by gmm96** [comment]
Changed data structures in shared.py to object oriented programming solution.
